kuka_blue:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
kuka_green:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001