kuka_blue:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 1.0
  kinematics_solver_attempts: 10
  mode: gd_c # use the gradient descent solver