# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - kuka_blue_A1
      - kuka_blue_A2
      - kuka_blue_A3
      - kuka_blue_A4
      - kuka_blue_A5
      - kuka_blue_A6
      - kuka_blue_A7
