# Default initial positions for iiwa7's ros2_control fake system

initial_positions:
  A1: 0
  A2: 0
  A3: 0
  A4: 0
  A5: 0
  A6: 0
  A7: 0
  aA1: 0
  aA2: 0
  aA3: 0
  aA4: 0
  aA5: 0
  aA6: 0
  aA7: 0