# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - iiwa_7_controller
    - kuka_blue_controller

  iiwa_7_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - aA1
      - aA2
      - aA3
      - aA4
      - aA5
      - aA6
      - aA7
  kuka_blue_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7