# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    iiwa_7_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    kuka_blue_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

iiwa_7_controller:
  ros__parameters:
    joints:
      - aA1
      - aA2
      - aA3
      - aA4
      - aA5
      - aA6
      - aA7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
kuka_blue_controller:
  ros__parameters:
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity